name: Running Code Coverage

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 

    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: ${{ matrix.node }} == 16
      with:
          token: ${{ secrets.CODECOV_TOKEN }}